# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    
    - task: NodeTaskRunnerInstaller@0
      inputs:
        nodeVersion: '6'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.dev'
        tags: |
          $(tag)

    - task: BeanstalkDeployApplication@1
      inputs:
         awsCredentials: 'aws-elasticbanstalk-deployment'
         regionName: 'us-east-1'
         applicationName: 'reactfrontend'
         environmentName: 'Reactfrontend-env'
         applicationType: 's3'
         deploymentBundleBucket: 'elasticbeanstalk-us-east-1-853110405500'
